version: '3.7'

networks:
  jenkins:
    driver: bridge
    
volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:

services:

  dind:
    image: docker:dind
    user: root
    privileged: true
    container_name: dind
    restart: always
    expose: 
      - 2376
    networks:
      jenkins:
        aliases: 
          - docker
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    user: root
    privileged: true
    container_name: jenkins
    restart: always
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
